apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "esaxo.labels" . | indent 4 }}
data:
{{- range .Files.Lines .Values.app.configfile }}
{{ . | indent 2 }}
{{- end }}
---
