apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
 name: {{ .Values.app.ingress.certName }}
 namespace: {{ .Values.app.ingress.istio.namespace }}
spec:
 vault:
   name: {{ .Values.app.ingress.istio.akvSecrets }}
   object:
     name: 
       esaxo-{{ .Values.app.containers.envCode }}-westus-aks-az-albertsons-com # is tthis aks name sapce?
     type: certificate
 output: 
   secret:
     name: {{ .Values.app.ingress.certName }} # kubernetes secret name
     type: {{ .Values.app.ingress.type }} # kubernetes secret type
     chainOrder: {{ .Values.app.ingress.chainOrder }}
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: awxpostgresdbpassword
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    name: {{ .Values.app.akvName }} # name of key vault
    object:
      name: {{ .Values.app.akvAbsDbPassword }} # name of the akv object
      type: secret # akv object type
  output:  #added to see if this pulls in the password from akv 
    secret: 
      name: {{ .Values.app.akvAbsDbPassword }} # kubernetes secret name
      dataKey: {{ .Values.app.akvAbsDbPassword }}-secret-value # key to store object value in kubernetes secret
---

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: akvawxadminpassword
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    name: {{ .Values.app.akvName }} # name of key vault
    object:
      name: {{ .Values.app.akvawxadminpassword }} # name of the akv object
      type: secret # akv object type
  output:  #added to see if this pulls in the password from akv 
    secret: 
      name: {{ .Values.app.akvawxadminpassword }} # kubernetes secret name
      dataKey: {{ .Values.app.akvawxadminpassword }}-secret-value # key to store object value in kubernetes secret
---
